#Numpy Numerical Python

In [ ]:
import numpy as np #alias np for numpy/object for numpy
a=np.array([12,3,5,7])
a

array([12,  3,  5,  7])

In [ ]:
#checking dimension of array
a.ndim #ndim n dimension

1

In [ ]:
#two dimension array
b=np.array([[1,2,3],[5,6,7]])
b
b.ndim

2

In [ ]:
#3-D array
arr=np.array([[[1,2,3],[1,4,3],[1,5,6]]])#no of dimension no of square brackets
arr

array([[[1, 2, 3],
        [1, 4, 3],
        [1, 5, 6]]])

In [ ]:
arr.ndim

3

#Zero's and One's

In [ ]:
z=np.zeros(10)
z#dot in o/p is float we give zero right

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
n=np.ones(7)
n#dont mind dot

array([1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# create a 3 D array with 4 rows 5 columns and all elements should be one
v=np.ones(5)
c=np.array([[v],[v],[v],[v]])
c


array([[[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]]])

In [ ]:
c.ndim

3

In [ ]:
s=np.ones((3,4,5)) # 3 dimension 4 rows 5 columns
s

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#Functions in numpy

In [ ]:
var=np.array([22,43,14,55,45])
var

array([22, 43, 14, 55, 45])

In [ ]:
type(var) #type

numpy.ndarray

In [ ]:
var.argmax() #max element index

3

In [ ]:
var.argmin() #min element index

2

In [ ]:
var[2]

14

In [ ]:
var1=np.array([22,43,14,55,45,12,98,75])
var1

array([22, 43, 14, 55, 45, 12, 98, 75])

In [ ]:
var1[:5]

array([22, 43, 14, 55, 45])

In [ ]:
var1[2:-2]# end is -2 means upto 12 only

array([14, 55, 45, 12])

In [ ]:
var1.dtype #data type of array elements

dtype('int64')

In [ ]:
var2=np.array([22.5,43,14,55,45])#one float all have point
var2

array([22.5, 43. , 14. , 55. , 45. ])

In [ ]:
var2.dtype

dtype('float64')

In [ ]:
var2.size #no of elements

5

In [ ]:
b1=np.array([1.2,2.3,3.4,4.5,5])
b1

array([1.2, 2.3, 3.4, 4.5, 5. ])

In [ ]:
#create 2 d array
#four arrays in external array
#2 elements each
f=np.array([[9,0],[8,7],[5,6],[3,4]])
f

array([[9, 0],
       [8, 7],
       [5, 6],
       [3, 4]])

#Resize and Reshape

In [ ]:
a1=np.arange(12) #range 12
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
x=np.arange(12).reshape(4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
x.max()

11

In [ ]:
x.min() #element argmin index

0

In [ ]:
np.sqrt(x)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])

In [ ]:
np.log(x)

<ipython-input-58-de666c833898>:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527]])

In [ ]:
np.exp(x)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [ ]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
x.shape # no of rows and columns

(4, 3)

#Transpose

In [ ]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
t=x.T
t

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [ ]:
t.shape

(3, 4)

#Floor and Ceiling

In [ ]:
g=np.array([10.3,3.42,5.6,1,8.9,2.3]) #8.9 check
g

array([10.3 ,  3.42,  5.6 ,  1.  ,  8.9 ,  2.3 ])

In [ ]:
np.floor(g) #takes integer park

array([10.,  3.,  5.,  1.,  8.,  2.])

In [ ]:
np.round(g)

array([10.,  3.,  6.,  1.,  9.,  2.])

In [ ]:
np.ceil(g)

array([11.,  4.,  6.,  1.,  9.,  3.])

#Stacking

In [ ]:
ar=np.arange(10).reshape(2,5)
ar

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
at=np.arange(20).reshape(4,5)
at

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
np.vstack((ar,at)) #vertical stack no of columns should be equal

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
h=np.arange(10).reshape(2,5)
h

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
i=np.arange(20).reshape(2,10)
i

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
np.hstack((h,i)) #horizontal stack #takes one argument so arrays are taken as tuple and tuple argument

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

#numpy split

In [ ]:
abc=np.arange(100).reshape(10,10)
abc

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
np.vsplit(abc,2) #vertical split

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [ ]:
np.hsplit(abc,2)#horizontal split

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44],
        [50, 51, 52, 53, 54],
        [60, 61, 62, 63, 64],
        [70, 71, 72, 73, 74],
        [80, 81, 82, 83, 84],
        [90, 91, 92, 93, 94]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29],
        [35, 36, 37, 38, 39],
        [45, 46, 47, 48, 49],
        [55, 56, 57, 58, 59],
        [65, 66, 67, 68, 69],
        [75, 76, 77, 78, 79],
        [85, 86, 87, 88, 89],
        [95, 96, 97, 98, 99]])]